CREATE SEQUENCE SEQ_POST_ID
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_COMMENT_ID
START WITH 1
INCREMENT BY 1;

CREATE TABLE MEMBER(
    NAME NVARCHAR2(20) NOT NULL,
    ID VARCHAR2(20) PRIMARY KEY,
    PASSWORD VARCHAR2(32) NOT NULL,
    NICKNAME NVARCHAR2(20) NOT NULL UNIQUE,
    EMAIL VARCHAR2(320) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    ROLE NUMBER DEFAULT 1
);

CREATE TABLE POST
(
    POST_ID NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) NOT NULL,
    WRITER NVARCHAR2(20) NOT NULL,
    TITLE NVARCHAR2(50) NOT NULL,
    CONTENT NCLOB NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    "LIKE" NUMBER DEFAULT 0,
    UNLIKE NUMBER DEFAULT 0,
    HIT NUMBER DEFAULT 0,
    CATEGORY NVARCHAR2(20),
    CONSTRAINT POST_MEMBER_ID FOREIGN KEY(MEMBER_ID) references "MEMBER" ("ID"),
    CONSTRAINT POST_WRITER FOREIGN KEY(WRITER) references "MEMBER" (NICKNAME)
);

CREATE TABLE "COMMENT"
(
    COMMENT_ID NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) NOT NULL,
    WRITER NVARCHAR2(20) NOT NULL,
    CONTENT NCLOB NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    POST_ID NUMBER NOT NULL,
    PARENT_ID NUMBER DEFAULT 0,
    CONSTRAINT COMMENT_POST_ID FOREIGN KEY(POST_ID) references POST ("POST_ID"),
    CONSTRAINT COMMENT_MEMBER_ID FOREIGN KEY(MEMBER_ID) references "MEMBER" ("ID"),
    CONSTRAINT COMMENT_WRITER FOREIGN KEY(WRITER) references "MEMBER" (NICKNAME)
);